### ISSUE TITLE
[fix] 배포작업 테스트 중 발견하게 된 오류 수정 작업 및 rankit 으로 변경됨에 인한 수정 작업 함께 진행

### ISSUE THREAD

**Issue by khyojun** [capstone-kw-jjiggle/rankit-be#180]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!

- api 테스트용으로 새로운 https, 도메인 적용시키면서 발견한 오류가 있었다. 이에 대하여 수정 작업을 진행한다.

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [x] User가 3000개가 들어가고 UserName 겹치는 경우 식별자 사용해 해결하기
- [x] swagger의 요청 보내는 칸에 있는 api.gitbal.xyz -> api.rankit.run 으로 변경하여 요청 서버로 날릴 수 있도록 하기
- [x] rankit 프로젝트 변경에 따른 네이밍들 수정 및 github 계정 옮김에 따른 작업 진행
- [x] url 변경에 따른 환경변수 수정작업들도 같이 진행

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- 
-
