### ISSUE TITLE
develop  branch blue-green 무중단 cicd 구현

### ISSUE THREAD

**Issue by leesj000603** [capstone-kw-jjiggle/rankit-be#205]
## 🛠️ 작업 설명
>github 푸시 이벤트 발생 시 자동 빌드 -> docker 이미지화 -> dockerhub 푸시 -> ec2에서 docker pull -> ec2에서 nginx와 shell script를 통해 blue-green 무중단 배포 구현

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [x] githubaction 스크립트 작성
- [x] blue용 dockercompose파일 작성
- [x] green용 dockercompose파일 작성
- [x] blue용 nginx conf 파일 작성
- [x] green용 nginx conf 파일 작성
- [x] blue, green container를 실행, swtiching하도록 해주는 shell script 작성 

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- 
-
