### ISSUE TITLE
[fix] fe api 연결시 발생한 1차 이슈 대응 

### ISSUE THREAD

**Issue by khyojun** [capstone-kw-jjiggle/rankit-be#209]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!

api 연결시 발생하였던 이슈들에 대해서 대응하기 위한 이슈입니다.

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [x] 일부 github 이미지 소스가 필요한 것들에 대한 친구들이 응답으로 값을 던지지 않고 있음! -> figma보고 없는 부분 채워서 전송
- [x] #211 에서 이후 진행
- [x]  #210 에서 이후 진행

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- 
-
