### ISSUE TITLE
[feat] 도메인 엔티티 만들기

### ISSUE THREAD

**Issue by khyojun** [capstone-kw-jjiggle/rankit-be#21]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!

각 엔티티 코드를 작성한다.

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [x] Spring Data JPA 라이브러리 불러오기
- [x] 각 엔티티별 설정 완료 (dbDiagram 보고 하기)
- [x] db 설정 파일은 ignore 로 숨기기
- [x] 단방향 매핑으로 수정작업 진행

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- https://dbdiagram.io/d/gitbal-65f6a636ae072629ce33cf4e
