### ISSUE TITLE
[feat] 유저당 페이지 관련하여 api 제작(/api/v1/userInfo?username=~~~) 및 MyPage api 명칭 변경 작업 진행

### ISSUE THREAD

**Issue by khyojun** [capstone-kw-jjiggle/rankit-be#211]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!

figma를 살펴본 이후 빼먹었던 api를 제작한다. 유저당 개인 페이지를 위한 유저 정보를 제공하여주는 api

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [x] 유저 정보 제공(유저 이름, 유저 grade, 유저 프로필 이미지) -> 언어는 이미 제공해주는 api가 있음
- [x] myPage 명칭 변경 -> 이제는 회원 전용 페이지가 아닌 모두가 볼 수 있는 페이지이기에!
- [x] 일부 api url 변경 진행 -> prefix에 userPage 가 붙고 my가 아닌 것들은 빼버리는 작업 진행

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- 
-
