### ISSUE TITLE
User Update 오류들 해결 작업

### ISSUE THREAD

**Issue by khyojun** [capstone-kw-jjiggle/rankit-be#217]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!

유저 관련 하여 업데이트 작업 진행하다가 생긴 처리한 오류에 대한 작업입니다.

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [x] 유저 주 언어 업데이트 진행시 제일 많이 사용한 언어가 아닌 언어가 오는 문제 해결
- [x] 유저 점수 업데이트 되지 않았던 부분 해결하기
- [x] userRanking 업데이트시 db에 정상적으로 저장되지 않는 오류 생성
- [x] login 진행시 redirect FE URL 로 갈 수 있도록 변경

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- 
-
