### ISSUE TITLE
isRegistered 파라미터 관련 처리 개선 -> 학교, 지역 보는것이 아닌 컬럼으로 

### ISSUE THREAD

**Issue by khyojun** [capstone-kw-jjiggle/rankit-be#219]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!

기존 로그인이 성공하고 신규 유저인지 아닌지에 대한 판단을 하였어야 하지만 
정책 변경으로 인하여 해당 신규유저 판단 로직을 개선한다.

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [x] 컬럼 추가를 통한 개선
- [x] 학교, 지역이 없더라도 진행할 수 있도록 처리하기! -> join 진행시
- [x] pr 올리기 이전 rds table 매핑할 수 있도록 컬럼 먼저 생성하기

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- 
-
