### ISSUE TITLE
MockData 300개 제작 및 발생한 오류들 수정

### ISSUE THREAD

**Issue by khyojun** [capstone-kw-jjiggle/rankit-be#220]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!

@jamooooong  가 제작한 imageUrl 을 활용하여서 Mock 데이터 생성할 수 있도록 하기

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [x] MockData 300개 제작하여 imgUrl 적용
- [x] swagger 요청 Url 잘못된 것 server.rankit.run 으로 수정
- [x] school, region 추가 시 createdAt 들어가지 않았던 문제 해결

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- 
-
