### ISSUE TITLE
frontend 이슈 대응 

### ISSUE THREAD

**Issue by leesj000603** [capstone-kw-jjiggle/rankit-be#222]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!
- mockdata img url 수정
- board 응답 갈때마다 " "  제외하도록
- isRegister 문제
-  my page 에서 region, school null로 응답가지 않도록
## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [x] mockdata img url 수정
- [ ] board 응답 갈때마다 " "  제외
- [ ] isRegister 문제 해결
- [ ] my page 에서 region, school null로 응답가지 않도록

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
