### ISSUE TITLE
[hotfix] fe 이슈 대응 - 지역 페이지네이션 및 게시판 조회 이슈 검토

### ISSUE THREAD

**Issue by khyojun** [capstone-kw-jjiggle/rankit-be#232]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!

Fe 에서 발생한 이슈에 페이지네이션 및 게시판 이슈에 대해서 대응하기 위한 이슈입니다.

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [x] 지역당 유저 검색시 10개씩 페이지네이션 되는 오류 해결 -> 14개로
- [x] 지역 검색시 10개씩 나오는 이슈 검토
- [x] 게시판 조회시 "" 추가로 조회되는 이슈 점검

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- 
-
